dim: 2
t_fin : 4.0 # diffusion duration
init_variance : 16.0 # N(0, init_variance * I_{dim}) is initial distribution
exps_count: 1 # count of repeated experiments
experiment_name: 'conv_comp_dim_2'
random_key: 'venus'
n_centers: 5
target_span: 5.0
target_std: 1.0
stationary_type: 'cube'
method:
    'ICNN_jko_dc':
        layer_width: 256
        n_layers: 2
        n_step_iterations: 500
        n_max_prop: 512
        dt: 0.1
        pretrain_lr: 8.e-3
        batch_size : 512
        lr:
        - - 20
          - 5.e-3
        - - 20
          - 2.e-3
        dt : 0.1 # jko approximation interval
        n_eval_samples : 8192 # samples to estimate KL
    'EM_sim_10000':
        dt: 1.e-3
        n_particles: 10000
        n_eval_samples: 8192 # samples to estimate KL